"""Add unique constraint to bookings

Revision ID: d13ab3e61870
Revises: 8b2269141265
Create Date: 2025-06-01 10:30:32.337500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd13ab3e61870'
down_revision: Union[str, None] = '8b2269141265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_booking_constraint', 'bookings', ['court_id', 'booking_date', 'time_slot'])
    op.drop_column('bookings', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_booking_constraint', 'bookings', type_='unique')
    # ### end Alembic commands ###
